---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Menü
- type: directory
  path: content/posts
  label: Postlar
  create: all
  match: "**/*"
  new_doc_ext: ''
  templates:
  - ayarlar
- type: document
  path: content/about
  label: Hakkımızda
- type: document
  path: content/tags
  label: Etiketler
- type: heading
  label: Ayarlamalar
- type: document
  path: config.toml
  label: Ayar
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_VERSION=0.62.0
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
